<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
          $countries = array(

        	// Records 01-99 (Afghanistan to India)

            array('country_name' => 'Afghanistan', 'country_code' => 'AFG'),
            array('country_name' => 'Albania', 'country_code' => 'ALB'),
            array('country_name' => 'Algeria', 'country_code' => 'DZA'),
            array('country_name' => 'American Samoa', 'country_code' => 'ASM'),
            array('country_name' => 'Andorra', 'country_code' => 'AND'),
            array('country_name' => 'Angola', 'country_code' => 'AGO'),
            array('country_name' => 'Anguilla', 'country_code' => 'AIA'),
            array('country_name' => 'Antarctica', 'country_code' => NULL),
            array('country_name' => 'Antigua and Barbuda', 'country_code' => 'ATG'),
            array('country_name' => 'Argentina', 'country_code' => 'ARG'),
            array('country_name' => 'Armenia', 'country_code' => 'ARM'),
            array('country_name' => 'Aruba', 'country_code' => 'ABW'),
            array('country_name' => 'Australia', 'country_code' => 'AUS'),
            array('country_name' => 'Austria', 'country_code' => 'AUT'),
            array('country_name' => 'Azerbaijan', 'country_code' => 'AZE'),
            array('country_name' => 'Bahamas', 'country_code' => 'BHS'),
            array('country_name' => 'Bahrain', 'country_code' => 'BHR'),
            array('country_name' => 'Bangladesh', 'country_code' => 'BGD'),
            array('country_name' => 'Barbados', 'country_code' => 'BRB'),
            array('country_name' => 'Belarus', 'country_code' => 'BLR'),
            array('country_name' => 'Belgium', 'country_code' => 'BEL'),
            array('country_name' => 'Belize', 'country_code' => 'BLZ'),
            array('country_name' => 'Benin', 'country_code' => 'BEN'),
            array('country_name' => 'Bermuda', 'country_code' => 'BMU'),
            array('country_name' => 'Bhutan', 'country_code' => 'BTN'),
            array('country_name' => 'Bolivia', 'country_code' => 'BOL'),
            array('country_name' => 'Bosnia and Herzegovina', 'country_code' => 'BIH'),
            array('country_name' => 'Botswana', 'country_code' => 'BWA'),
            array('country_name' => 'Bouvet Island', 'country_code' => NULL),
            array('country_name' => 'Brazil', 'country_code' => 'BRA'),
            array('country_name' => 'British Indian Ocean Territory', 'country_code' => NULL),
            array('country_name' => 'Brunei Darussalam', 'country_code' => 'BRN'),
            array('country_name' => 'Bulgaria', 'country_code' => 'BGR'),
            array('country_name' => 'Burkina Faso', 'country_code' => 'BFA'),
            array('country_name' => 'Burundi', 'country_code' => 'BDI'),
            array('country_name' => 'Cambodia', 'country_code' => 'KHM'),
            array('country_name' => 'Cameroon', 'country_code' => 'CMR'),
            array('country_name' => 'Canada', 'country_code' => 'CAN'),
            array('country_name' => 'Cape Verde', 'country_code' => 'CPV'),
            array('country_name' => 'Cayman Islands', 'country_code' => 'CYM'),
            array('country_name' => 'Central African Republic', 'country_code' => 'CAF'),
            array('country_name' => 'Chad', 'country_code' => 'TCD'),
            array('country_name' => 'Chile', 'country_code' => 'CHL'),
            array('country_name' => 'China', 'country_code' => 'CHN'),
            array('country_name' => 'Christmas Island', 'country_code' => NULL),
            array('country_name' => 'Cocos (Keeling) Islands', 'country_code' => NULL),
            array('country_name' => 'Colombia', 'country_code' => 'COL'),
            array('country_name' => 'Comoros', 'country_code' => 'COM'),
            array('country_name' => 'Congo', 'country_code' => 'COG'),
            array('country_name' => 'Congo, the Democratic Republic of the', 'country_code' => 'COD'),
            array('country_name' => 'Cook Islands', 'country_code' => 'COK'),
            array('country_name' => 'Costa Rica', 'country_code' => 'CRI'),
            array('country_name' => 'Cote D\'Ivoire', 'country_code' => 'CIV'),
            array('country_name' => 'Croatia', 'country_code' => 'HRV'),
            array('country_name' => 'Cuba', 'country_code' => 'CUB'),
            array('country_name' => 'Cyprus', 'country_code' => 'CYP'),
            array('country_name' => 'Czech Republic', 'country_code' => 'CZE'),
            array('country_name' => 'Denmark', 'country_code' => 'DNK'),
            array('country_name' => 'Djibouti', 'country_code' => 'DJI'),
            array('country_name' => 'Dominica', 'country_code' => 'DMA'),
            array('country_name' => 'Dominican Republic', 'country_code' => 'DOM'),
            array('country_name' => 'Ecuador', 'country_code' => 'ECU'),
            array('country_name' => 'Egypt', 'country_code' => 'EGY'),
            array('country_name' => 'El Salvador', 'country_code' => 'SLV'),
            array('country_name' => 'Equatorial Guinea', 'country_code' => 'GNQ'),
            array('country_name' => 'Eritrea', 'country_code' => 'ERI'),
            array('country_name' => 'Estonia', 'country_code' => 'EST'),
            array('country_name' => 'Ethiopia', 'country_code' => 'ETH'),
            array('country_name' => 'Falkland Islands (Malvinas)', 'country_code' => 'FLK'),
            array('country_name' => 'Faroe Islands', 'country_code' => 'FRO'),
            array('country_name' => 'Fiji', 'country_code' => 'FJI'),
            array('country_name' => 'Finland', 'country_code' => 'FIN'),
            array('country_name' => 'France', 'country_code' => 'FRA'),
            array('country_name' => 'French Guiana', 'country_code' => 'GUF'),
            array('country_name' => 'French Polynesia', 'country_code' => 'PYF'),
            array('country_name' => 'French Southern Territories', 'country_code' => NULL),
            array('country_name' => 'Gabon', 'country_code' => 'GAB'),
            array('country_name' => 'Gambia', 'country_code' => 'GMB'),
            array('country_name' => 'Georgia', 'country_code' => 'GEO'),
            array('country_name' => 'Germany', 'country_code' => 'DEU'),
            array('country_name' => 'Ghana', 'country_code' => 'GHA'),
            array('country_name' => 'Gibraltar', 'country_code' => 'GIB'),
            array('country_name' => 'Greece', 'country_code' => 'GRC'),
            array('country_name' => 'Greenland', 'country_code' => 'GRL'),
            array('country_name' => 'Grenada', 'country_code' => 'GRD'),
            array('country_name' => 'Guadeloupe', 'country_code' => 'GLP'),
            array('country_name' => 'Guam', 'country_code' => 'GUM'),
            array('country_name' => 'Guatemala', 'country_code' => 'GTM'),
            array('country_name' => 'Guinea', 'country_code' => 'GIN'),
            array('country_name' => 'Guinea-Bissau', 'country_code' => 'GNB'),
            array('country_name' => 'Guyana', 'country_code' => 'GUY'),
            array('country_name' => 'Haiti', 'country_code' => 'HTI'),
            array('country_name' => 'Heard Island and Mcdonald Islands', 'country_code' => NULL),
            array('country_name' => 'Holy See (Vatican City State)', 'country_code' => 'VAT'),
            array('country_name' => 'Honduras', 'country_code' => 'HND'),
            array('country_name' => 'Hong Kong', 'country_code' => 'HKG'),
            array('country_name' => 'Hungary', 'country_code' => 'HUN'),
            array('country_name' => 'Iceland', 'country_code' => 'ISL'),
            array('country_name' => 'India', 'country_code' => 'IND'),


            // Records 100-199 (Indonesia to Spain)

            array('country_name' => 'Indonesia', 'country_code' => 'IDN'),
            array('country_name' => 'Iran, Islamic Republic of', 'country_code' => 'IRN'),
            array('country_name' => 'Iraq', 'country_code' => 'IRQ'),
            array('country_name' => 'Ireland', 'country_code' => 'IRL'),
            array('country_name' => 'Israel', 'country_code' => 'ISR'),
            array('country_name' => 'Italy', 'country_code' => 'ITA'),
            array('country_name' => 'Jamaica', 'country_code' => 'JAM'),
            array('country_name' => 'Japan', 'country_code' => 'JPN'),
            array('country_name' => 'Jordan', 'country_code' => 'JOR'),
            array('country_name' => 'Kazakhstan', 'country_code' => 'KAZ'),
            array('country_name' => 'Kenya', 'country_code' => 'KEN'),
            array('country_name' => 'Kiribati', 'country_code' => 'KIR'),
            array('country_name' => 'Korea, Democratic People\'s Republic of', 'country_code' => 'PRK'),
            array('country_name' => 'Korea, Republic of', 'country_code' => 'KOR'),
            array('country_name' => 'Kuwait', 'country_code' => 'KWT'),
            array('country_name' => 'Kyrgyzstan', 'country_code' => 'KGZ'),
            array('country_name' => 'Lao People\'s Democratic Republic', 'country_code' => 'LAO'),
            array('country_name' => 'Latvia', 'country_code' => 'LVA'),
            array('country_name' => 'Lebanon', 'country_code' => 'LBN'),
            array('country_name' => 'Lesotho', 'country_code' => 'LSO'),
            array('country_name' => 'Liberia', 'country_code' => 'LBR'),
            array('country_name' => 'Libyan Arab Jamahiriya', 'country_code' => 'LBY'),
            array('country_name' => 'Liechtenstein', 'country_code' => 'LIE'),
            array('country_name' => 'Lithuania', 'country_code' => 'LTU'),
            array('country_name' => 'Luxembourg', 'country_code' => 'LUX'),
            array('country_name' => 'Macao', 'country_code' => 'MAC'),
            array('country_name' => 'Macedonia, the Former Yugoslav Republic of', 'country_code' => 'MKD'),
            array('country_name' => 'Madagascar', 'country_code' => 'MDG'),
            array('country_name' => 'Malawi', 'country_code' => 'MWI'),
            array('country_name' => 'Malaysia', 'country_code' => 'MYS'),
            array('country_name' => 'Maldives', 'country_code' => 'MDV'),
            array('country_name' => 'Mali', 'country_code' => 'MLI'),
            array('country_name' => 'Malta', 'country_code' => 'MLT'),
            array('country_name' => 'Marshall Islands', 'country_code' => 'MHL'),
            array('country_name' => 'Martinique', 'country_code' => 'MTQ'),
            array('country_name' => 'Mauritania', 'country_code' => 'MRT'),
            array('country_name' => 'Mauritius', 'country_code' => 'MUS'),
            array('country_name' => 'Mayotte', 'country_code' => NULL),
            array('country_name' => 'Mexico', 'country_code' => 'MEX'),
            array('country_name' => 'Micronesia, Federated States of', 'country_code' => 'FSM'),
            array('country_name' => 'Moldova, Republic of', 'country_code' => 'MDA'),
            array('country_name' => 'Monaco', 'country_code' => 'MCO'),
            array('country_name' => 'Mongolia', 'country_code' => 'MNG'),
            array('country_name' => 'Montserrat', 'country_code' => 'MSR'),
            array('country_name' => 'Morocco', 'country_code' => 'MAR'),
            array('country_name' => 'Mozambique', 'country_code' => 'MOZ'),
            array('country_name' => 'Myanmar', 'country_code' => 'MMR'),
            array('country_name' => 'Namibia', 'country_code' => 'NAM'),
            array('country_name' => 'Nauru', 'country_code' => 'NRU'),
            array('country_name' => 'Nepal', 'country_code' => 'NPL'),
            array('country_name' => 'Netherlands', 'country_code' => 'NLD'),
            array('country_name' => 'Netherlands Antilles', 'country_code' => 'ANT'),
            array('country_name' => 'New Caledonia', 'country_code' => 'NCL'),
            array('country_name' => 'New Zealand', 'country_code' => 'NZL'),
            array('country_name' => 'Nicaragua', 'country_code' => 'NIC'),
            array('country_name' => 'Niger', 'country_code' => 'NER'),
            array('country_name' => 'Nigeria', 'country_code' => 'NGA'),
            array('country_name' => 'Niue', 'country_code' => 'NIU'),
            array('country_name' => 'Norfolk Island', 'country_code' => 'NFK'),
            array('country_name' => 'Northern Mariana Islands', 'country_code' => 'MNP'),
            array('country_name' => 'Norway', 'country_code' => 'NOR'),
            array('country_name' => 'Oman', 'country_code' => 'OMN'),
            array('country_name' => 'Pakistan', 'country_code' => 'PAK'),
            array('country_name' => 'Palau', 'country_code' => 'PLW'),
            array('country_name' => 'Palestinian Territory, Occupied', 'country_code' => NULL),
            array('country_name' => 'Panama', 'country_code' => 'PAN'),
            array('country_name' => 'Papua New Guinea', 'country_code' => 'PNG'),
            array('country_name' => 'Paraguay', 'country_code' => 'PRY'),
            array('country_name' => 'Peru', 'country_code' => 'PER'),
            array('country_name' => 'Philippines', 'country_code' => 'PHL'),
            array('country_name' => 'Pitcairn', 'country_code' => 'PCN'),
            array('country_name' => 'Poland', 'country_code' => 'POL'),
            array('country_name' => 'Portugal', 'country_code' => 'PRT'),
            array('country_name' => 'Puerto Rico', 'country_code' => 'PRI'),
            array('country_name' => 'Qatar', 'country_code' => 'QAT'),
            array('country_name' => 'Reunion', 'country_code' => 'REU'),
            array('country_name' => 'Romania', 'country_code' => 'ROM'),
            array('country_name' => 'Russian Federation', 'country_code' => 'RUS'),
            array('country_name' => 'Rwanda', 'country_code' => 'RWA'),
            array('country_name' => 'Saint Helena', 'country_code' => 'SHN'),
            array('country_name' => 'Saint Kitts and Nevis', 'country_code' => 'KNA'),
            array('country_name' => 'Saint Lucia', 'country_code' => 'LCA'),
            array('country_name' => 'Saint Pierre and Miquelon', 'country_code' => 'SPM'),
            array('country_name' => 'Saint Vincent and the Grenadines', 'country_code' => 'VCT'),
            array('country_name' => 'Samoa', 'country_code' => 'WSM'),
            array('country_name' => 'San Marino', 'country_code' => 'SMR'),
            array('country_name' => 'Sao Tome and Principe', 'country_code' => 'STP'),
            array('country_name' => 'Saudi Arabia', 'country_code' => 'SAU'),
            array('country_name' => 'Senegal', 'country_code' => 'SEN'),
            array('country_name' => 'Serbia and Montenegro', 'country_code' => NULL),
            array('country_name' => 'Seychelles', 'country_code' => 'SYC'),
            array('country_name' => 'Sierra Leone', 'country_code' => 'SLE'),
            array('country_name' => 'Singapore', 'country_code' => 'SGP'),
            array('country_name' => 'Slovakia', 'country_code' => 'SVK'),
            array('country_name' => 'Slovenia', 'country_code' => 'SVN'),
            array('country_name' => 'Solomon Islands', 'country_code' => 'SLB'),
            array('country_name' => 'Somalia', 'country_code' => 'SOM'),
            array('country_name' => 'South Africa', 'country_code' => 'ZAF'),
            array('country_name' => 'South Georgia and the South Sandwich Islands', 'country_code' => NULL),
            array('country_name' => 'Spain', 'country_code' => 'ESP'),


            // Records 200-253 (Sri Lanka to South Sudan)

            array('country_name' => 'Sri Lanka', 'country_code' => 'LKA'),
            array('country_name' => 'Sudan', 'country_code' => 'SDN'),
            array('country_name' => 'Suriname', 'country_code' => 'SUR'),
            array('country_name' => 'Svalbard and Jan Mayen', 'country_code' => 'SJM'),
            array('country_name' => 'Swaziland', 'country_code' => 'SWZ'),
            array('country_name' => 'Sweden', 'country_code' => 'SWE'),
            array('country_name' => 'Switzerland', 'country_code' => 'CHE'),
            array('country_name' => 'Syrian Arab Republic', 'country_code' => 'SYR'),
            array('country_name' => 'Taiwan, Province of China', 'country_code' => 'TWN'),
            array('country_name' => 'Tajikistan', 'country_code' => 'TJK'),
            array('country_name' => 'Tanzania, United Republic of', 'country_code' => 'TZA'),
            array('country_name' => 'Thailand', 'country_code' => 'THA'),
            array('country_name' => 'Timor-Leste', 'country_code' => NULL),
            array('country_name' => 'Togo', 'country_code' => 'TGO'),
            array('country_name' => 'Tokelau', 'country_code' => 'TKL'),
            array('country_name' => 'Tonga', 'country_code' => 'TON'),
            array('country_name' => 'Trinidad and Tobago', 'country_code' => 'TTO'),
            array('country_name' => 'Tunisia', 'country_code' => 'TUN'),
            array('country_name' => 'Turkey', 'country_code' => 'TUR'),
            array('country_name' => 'Turkmenistan', 'country_code' => 'TKM'),
            array('country_name' => 'Turks and Caicos Islands', 'country_code' => 'TCA'),
            array('country_name' => 'Tuvalu', 'country_code' => 'TUV'),
            array('country_name' => 'Uganda', 'country_code' => 'UGA'),
            array('country_name' => 'Ukraine', 'country_code' => 'UKR'),
            array('country_name' => 'United Arab Emirates', 'country_code' => 'ARE'),
            array('country_name' => 'United Kingdom', 'country_code' => 'GBR'),
            array('country_name' => 'United States', 'country_code' => 'USA'),
            array('country_name' => 'United States Minor Outlying Islands', 'country_code' => NULL),
            array('country_name' => 'Uruguay', 'country_code' => 'URY'),
            array('country_name' => 'Uzbekistan', 'country_code' => 'UZB'),
            array('country_name' => 'Vanuatu', 'country_code' => 'VUT'),
            array('country_name' => 'Venezuela', 'country_code' => 'VEN'),
            array('country_name' => 'Viet Nam', 'country_code' => 'VNM'),
            array('country_name' => 'Virgin Islands, British', 'country_code' => 'VGB'),
            array('country_name' => 'Virgin Islands, U.S.', 'country_code' => 'VIR'),
            array('country_name' => 'Wallis and Futuna', 'country_code' => 'WLF'),
            array('country_name' => 'Western Sahara', 'country_code' => 'ESH'),
            array('country_name' => 'Yemen', 'country_code' => 'YEM'),
            array('country_name' => 'Zambia', 'country_code' => 'ZMB'),
            array('country_name' => 'Zimbabwe', 'country_code' => 'ZWE'),
            array('country_name' => 'Serbia', 'country_code' => 'SRB'),
            array('country_name' => 'Asia / Pacific Region', 'country_code' => '0'),
            array('country_name' => 'Montenegro', 'country_code' => 'MNE'),
            array('country_name' => 'Aland Islands', 'country_code' => 'ALA'),
            array('country_name' => 'Bonaire, Sint Eustatius and Saba', 'country_code' => 'BES'),
            array('country_name' => 'Curacao', 'country_code' => 'CUW'),
            array('country_name' => 'Guernsey', 'country_code' => 'GGY'),
            array('country_name' => 'Isle of Man', 'country_code' => 'IMN'),
            array('country_name' => 'Jersey', 'country_code' => 'JEY'),
            array('country_name' => 'Kosovo', 'country_code' => '---'),
            array('country_name' => 'Saint Barthelemy', 'country_code' => 'BLM'),
            array('country_name' => 'Saint Martin', 'country_code' => 'MAF'),
            array('country_name' => 'Sint Maarten', 'country_code' => 'SXM'),
            array('country_name' => 'South Sudan', 'country_code' => 'SSD')
          );


        foreach ($countries as $country) {
            DB::table('countries')->updateOrInsert(
                ['country_code' => $country['country_code']],
                ['country_name' => $country['country_name']]
            );
        }
    }
}
